<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank Reconciliation Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .report-subtitle {
            font-size: 14px;
            color: #666;
            margin-bottom: 10px;
        }
        .info-section {
            margin-bottom: 20px;
        }
        .info-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        .info-label {
            font-weight: bold;
            width: 150px;
        }
        .info-value {
            flex: 1;
        }
        .filters-section {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .filters-title {
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }
        .filter-item {
            margin-bottom: 5px;
        }
        .stats-section {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .stat-box {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
            flex: 1;
            margin: 0 5px;
        }
        .stat-value {
            font-size: 18px;
            font-weight: bold;
            color: #333;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .status-badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .status-draft { background-color: #6c757d; color: white; }
        .status-in_progress { background-color: #ffc107; color: black; }
        .status-completed { background-color: #28a745; color: white; }
        .status-cancelled { background-color: #dc3545; color: white; }
        .balanced { color: #28a745; font-weight: bold; }
        .unbalanced { color: #dc3545; font-weight: bold; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <div class="company-name">{{ $company->name ?? 'SmartFinance' }}</div>
        <div class="report-title">Bank Reconciliation Report</div>
        <div class="report-subtitle">Generated on {{ $generated_at->format('M d, Y \a\t H:i') }}</div>
    </div>

    <!-- Report Information -->
    <div class="info-section">
        <div class="info-row">
            <span class="info-label">Branch:</span>
            <span class="info-value">{{ $branch->name ?? 'N/A' }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Generated By:</span>
            <span class="info-value">{{ $user->name }}</span>
        </div>
        <div class="info-row">
            <span class="info-label">Report Period:</span>
            <span class="info-value">
                @if($filters['start_date'] && $filters['end_date'])
                    {{ \Carbon\Carbon::parse($filters['start_date'])->format('M d, Y') }} - {{ \Carbon\Carbon::parse($filters['end_date'])->format('M d, Y') }}
                @else
                    All Time
                @endif
            </span>
        </div>
    </div>

    <!-- Filters Applied -->
    @if(!empty(array_filter($filters)))
    <div class="filters-section">
        <div class="filters-title">Filters Applied:</div>
        @if($filters['bank_account_id'])
            <div class="filter-item">
                <strong>Bank Account:</strong> 
                @php
                    $bankAccount = $reconciliations->first()->bankAccount ?? null;
                @endphp
                {{ $bankAccount ? $bankAccount->name : 'Specific Account' }}
            </div>
        @endif
        @if($filters['start_date'])
            <div class="filter-item">
                <strong>Start Date:</strong> {{ \Carbon\Carbon::parse($filters['start_date'])->format('M d, Y') }}
            </div>
        @endif
        @if($filters['end_date'])
            <div class="filter-item">
                <strong>End Date:</strong> {{ \Carbon\Carbon::parse($filters['end_date'])->format('M d, Y') }}
            </div>
        @endif
        @if($filters['status'])
            <div class="filter-item">
                <strong>Status:</strong> {{ ucfirst(str_replace('_', ' ', $filters['status'])) }}
            </div>
        @endif
    </div>
    @endif

    <!-- Statistics -->
    <div class="stats-section">
        <div class="stat-box">
            <div class="stat-value">{{ $reportStats['total_reconciliations'] }}</div>
            <div class="stat-label">Total Reconciliations</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ number_format($reportStats['total_bank_balance'], 2) }}</div>
            <div class="stat-label">Total Bank Balance</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ number_format($reportStats['total_book_balance'], 2) }}</div>
            <div class="stat-label">Total Book Balance</div>
        </div>
        <div class="stat-box">
            <div class="stat-value {{ $reportStats['total_difference'] == 0 ? 'balanced' : 'unbalanced' }}">
                {{ number_format($reportStats['total_difference'], 2) }}
            </div>
            <div class="stat-label">Total Difference</div>
        </div>
    </div>

    <!-- Reconciliation Details -->
    <table>
        <thead>
            <tr>
                <th>Bank Account</th>
                <th>Reconciliation Date</th>
                <th>Period</th>
                <th class="text-right">Bank Statement Balance</th>
                <th class="text-right">Book Balance</th>
                <th class="text-right">Difference</th>
                <th class="text-center">Status</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reconciliations as $reconciliation)
            <tr>
                <td>
                    <strong>{{ $reconciliation->bankAccount->name }}</strong><br>
                    <small>{{ $reconciliation->bankAccount->account_number }}</small>
                </td>
                <td>{{ $reconciliation->reconciliation_date->format('M d, Y') }}</td>
                <td>
                    {{ $reconciliation->start_date->format('M d, Y') }} - {{ $reconciliation->end_date->format('M d, Y') }}
                </td>
                <td class="text-right">{{ number_format($reconciliation->bank_statement_balance, 2) }}</td>
                <td class="text-right">{{ number_format($reconciliation->book_balance, 2) }}</td>
                <td class="text-right {{ $reconciliation->difference == 0 ? 'balanced' : 'unbalanced' }}">
                    @if($reconciliation->difference == 0)
                        Balanced
                    @else
                        {{ number_format($reconciliation->difference, 2) }}
                    @endif
                </td>
                <td class="text-center">
                    <span class="status-badge status-{{ $reconciliation->status }}">
                        {{ ucfirst(str_replace('_', ' ', $reconciliation->status)) }}
                    </span>
                </td>
                <td>
                    {{ $reconciliation->user->name }}<br>
                    <small>{{ $reconciliation->created_at->format('M d, Y') }}</small>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="8" class="text-center">No reconciliations found for the selected criteria.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Summary by Status -->
    @if($reconciliations->count() > 0)
    <div class="page-break"></div>
    <h3>Summary by Status</h3>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th class="text-center">Count</th>
                <th class="text-right">Total Bank Balance</th>
                <th class="text-right">Total Book Balance</th>
                <th class="text-right">Total Difference</th>
            </tr>
        </thead>
        <tbody>
            @php
                $statusGroups = $reconciliations->groupBy('status');
            @endphp
            @foreach($statusGroups as $status => $group)
            <tr>
                <td>
                    <span class="status-badge status-{{ $status }}">
                        {{ ucfirst(str_replace('_', ' ', $status)) }}
                    </span>
                </td>
                <td class="text-center">{{ $group->count() }}</td>
                <td class="text-right">{{ number_format($group->sum('bank_statement_balance'), 2) }}</td>
                <td class="text-right">{{ number_format($group->sum('book_balance'), 2) }}</td>
                <td class="text-right {{ $group->sum('difference') == 0 ? 'balanced' : 'unbalanced' }}">
                    {{ number_format($group->sum('difference'), 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p>This report was generated by {{ $user->name }} on {{ $generated_at->format('M d, Y \a\t H:i:s') }}</p>
        <p>SmartFinance - Bank Reconciliation Report</p>
    </div>
</body>
</html> 